### ISSUE TITLE
Items are removed from shopping cart once the order is placed

### ISSUE THREAD

**Issue by alvaroperezc** [CSCI-GA-2820-SP24-001/shopcarts#7] opened 2024-02-19 18:09 UTC
**As a** user
**I need** to have the items I have purchased deleted from the shopping cart 
**So that** I don't duplicate my purchase in the future 
   
 ### Details and Assumptions
 * Once a user purchases a product, we assume that if they would like for it to be deleted from their shopping cart
 * Information needs to flow from the order management system so shopping cart logic can make the deletions requested
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that a user purchases items in their shopping cart
 When a transaction is confirmed
 Then all items purchased will be automatically deleted from the shopping cart
```

**Comment by whykay-01** [comment] 2024-02-21 19:56
brainstorm more about this one (flow-wise)

**Comment by whykay-01** [comment] 2024-02-23 16:42
closing this issue because it is a duplicate of the DELETE item issue, which is already in the sprint 1 backlog

**Closed** 2024-04-01 18:41 UTC
Labels: enhancement
